### ISSUE TITLE
ext-crypto

### ISSUE THREAD

**Issue by snzmnrdn** [cmnty/php-push#7]
My Ubuntu dont have this module

Error output in composer

```
  Problem 1
    - Installation request for cmnty/push ^0.0.1 -> satisfiable by cmnty/push[0.0.1].
    - cmnty/push 0.0.1 requires ext-crypto * -> the requested PHP extension crypto is missing from your system.
```

even with
`sudo apt-get install php7.0-crypto`

**Comment by johanderuijter** [comment]
Seems like an issue with your system, not this library.

When you run `php -m` (or `php -m | grep crypto`) is it listed as an installed extension? If it's not listed, it isn't installed / loaded as an extension.

If not, is you cli running the php version you expect it to. Some distributions have different configuration files for different environments. Please see https://github.com/bukka/php-crypto for installation details for the extension. I dont use ubuntu myself, not sure how much help i can be here?

**Comment by snzmnrdn** [comment]
I successfully install crypto library as you suggested.
